# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "timer app"
client_id = "b87ea5608bf3f5d66f43f6f3112167bb"
application_url = "https://encouraging-fiscal-jj-powder.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://encouraging-fiscal-jj-powder.trycloudflare.com/auth/callback",
  "https://encouraging-fiscal-jj-powder.trycloudflare.com/auth/shopify/callback",
  "https://encouraging-fiscal-jj-powder.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dracoslides123.myshopify.com"
