# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2023-07"

[[extensions]]
type = "ui_extension"
name = "timer ext"
handle = "timer-ext"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
 [settings]
   [[settings.fields]]
   key = "timer_before_text"
   type = "single_line_text_field"
   name = "Timer Before Text"
   description = "This Offer Ends In"

   [[settings.fields]]
   key = "timer_after_text"
   type = "single_line_text_field"
   name = "Timer After Text"
   description = "Minutes"

   [[settings.fields]]
   key = "timer"
   type = "single_line_text_field"
   name = "Timer"
   description = "Please Put The Remaining Minutes For Example ( 15 )"

   [[settings.fields]]
   key = "timer_ends"
   type = "single_line_text_field"
   name = "Timer End Text"
   description = "You Can Add Timer End Text Here"

    [[settings.fields]]
  key = "timer_text_color"
  type = "single_line_text_field"
  name = "Timer Text Color"
  description = "Select The Color Of Timer Text"
    [[settings.fields.validations]]
    name = "choices"
     value = '["accent", "critical", "info", "subdued", "success", "warning", "interactive", "monochrome"]'

  [[settings.fields]]
  key = "timer_text_size"
  type = "single_line_text_field"
  name = "Timer Text Size"
  description = "Select The Size Of Timer Text"
    [[settings.fields.validations]]
    name = "choices"
     value = '["base", "extralarge", "extrasmall", "large", "medium", "small"]'

  [[settings.fields]]
  key = "timer_color"
  type = "single_line_text_field"
  name = "Timer Color"
  description = "Select Timer Color"
    [[settings.fields.validations]]
    name = "choices"
     value = '["accent", "critical", "info", "subdued", "success", "warning", "interactive", "monochrome"]'

  [[settings.fields]]
  key = "timer_size"
  type = "single_line_text_field"
  name = "Timer Size"
  description = "Select Timer Size"
    [[settings.fields.validations]]
    name = "choices"
     value = '["base", "extralarge", "extrasmall", "large", "medium", "small"]'
